sculpin:
  output_dir: docs
  source_dir: src
  ignore: ['**/_scss/','**/_includes/','**/_js/']
sculpin_content_types:
    posts:
        permalink: pretty
sculpin_twig:
    source_view_paths: ['_app', '_blocks', '_components', '_css', '_includes', '_layouts', '_themes']
